# Generated by Django 5.0.1 on 2024-08-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.ManyToManyField(related_name='products', to='product_app.productcategory'),
        ),
    ]
