# Generated by Django 5.0.7 on 2024-09-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_remove_product_category_name_product_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description_tm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_name_tm',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
