# Generated by Django 5.0.7 on 2024-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_product_product_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_tm',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
