# Generated by Django 5.0.7 on 2024-08-25 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_app', '0001_initial'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LikeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='like_app.like')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='product_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='products',
            field=models.ManyToManyField(through='like_app.LikeItem', to='product_app.product'),
        ),
    ]
