# Generated by Django 5.0.1 on 2024-08-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_brand',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
