# Generated by Django 5.0.7 on 2024-09-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0002_advertisement_is_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
