# Generated by Django 5.0.7 on 2024-09-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0003_alter_advertisement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
